server {
    listen 80;
    listen [::]:80;
    server_name agent.funnet.kr;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name agent.funnet.kr;

    access_log /data/logs/nginx/agent.funnet.kr.access.log main;
    error_log /data/logs/nginx/agent.funnet.kr.error.log;

    ssl_certificate /data/cert/funnet.kr/funnet.kr.all.crt.pem;
    ssl_certificate_key /data/cert/funnet.kr/funnet.kr.key;
    ssl_session_timeout 5m;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    client_max_body_size 512m;

    location / {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header proxied nginx;
        proxy_pass_request_headers on;
        proxy_buffering off;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;

        proxy_pass http://127.0.0.1:4170;
    }
}
